#define DEFAULT_SPEED 500
#define INTERSECTION_SPEED 400

#define STOP_DISTANCE_CLOSE 30
#define STOP_DISTANCE_MID 50
#define STOP_DISTANCE_FAR 70

#define OBST_DISTANCE_CLOSE 90

#define EXPECTED_ANGLE_THESHOLD 20

